# Docker Compose file for production

version: '3'
services:
  nginx: 
    image: nginx
    volumes:
      - "./etc/nginx/gan-hattra.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "./frontend:/var/www"
    ports:
      - "3002:80"
    restart: always
  app:
    build: .
    command: 'node server.js'
    depends_on:
      - mysql
      - redis
      - rethinkdb
    volumes: # TODO: use in-container files instead in production (?)
      - .:/usr/src/e-gov-jabar
      - /usr/src/e-gov-jabar/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production # TODO: change this to 'production' on production
      EGOV_API_PORT: 3000
      EGOV_API_SECRET: "[ e-gov_jabar_secret ]" # TODO: change this on production
      MYSQL_HOST: mysql
      MYSQL_USER: egov-jabar
      MYSQL_PASSWORD: "[ mysql_password ]" # TODO: change this to a strong password on production, must match with mysql
      MYSQL_DATABASE: egov-jabar
      REDIS_HOST: redis
      REDIS_PORT: 6379 # Using default redis image port
    restart: always # TODO: change this to 'always' on production
  mysql:
    image: "mysql"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "[ mysql_root_password ]" # TODO: change this to a strong password on production, for administration purposes
      MYSQL_DATABASE: egov-jabar
      MYSQL_USER: egov-jabar
      MYSQL_PASSWORD: "[ mysql_password ]" # TODO: change this to a strong password on production, must match with app
    restart: on-failure # TODO: change this to 'always' on production
  redis:
    image: "redis:alpine"
    restart: on-failure # TODO: change this to 'always' on production
  myadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
        - "3001:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
    restart: always
    depends_on:
        - mysql
  rethinkdb:
    image: rethinkdb
    restart: always
    ports:
        - "28015:28015"
