# Docker Compose file for production

version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - "./etc/nginx/gan-hattra.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "./frontend:/var/www"
    ports:
      - "3000:80"
    restart: always
  app:
    build: .
    command: 'node server.js'
    depends_on:
      - mysql
      - redis
      - rethinkdb
    volumes:
      - .:/usr/src/e-gov-jabar
      - /usr/src/e-gov-jabar/node_modules
    environment:
      NODE_ENV: production
      EGOV_API_PORT: 3000
      EGOV_API_SECRET: "[ e-gov_jabar_secret ]"
      MYSQL_HOST: mysql
      MYSQL_USER: egov-jabar
      MYSQL_PASSWORD: "[ mysql_password ]"
      MYSQL_DATABASE: egov-jabar
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always
  mysql:
    image: "mysql"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "[ mysql_root_password ]"
      MYSQL_DATABASE: egov-jabar
      MYSQL_USER: egov-jabar
      MYSQL_PASSWORD: "[ mysql_password ]"
    restart: on-failure
  redis:
    image: "redis:alpine"
    restart: on-failure
  myadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
        - "3001:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
    restart: always
    depends_on:
        - mysql
  #rethinkdb:
  #  image: rethinkdb
  #  restart: always
  #  ports:
  #      - "28015:28015"
