# Docker Compose file for development

version: '3'
services:
  app:
    build: .
    command: 'node_modules/.bin/nodemon'
    depends_on:
      - mysql
      - redis
      # - rethinkdb
    volumes: # TODO: use in-container files instead in production (?)
      - .:/usr/src/e-gov-jabar
      - /usr/src/e-gov-jabar/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development # TODO: change this to 'production' on production
      EGOV_API_PORT: 3000
      EGOV_API_SECRET: "[ e-gov_jabar_secret ]" # TODO: change this on production
      MYSQL_HOST: mysql
      MYSQL_USER: egov-jabar
      MYSQL_PASSWORD: "[ mysql_password ]" # TODO: change this to a strong password on production, must match with mysql
      MYSQL_DATABASE: egov-jabar
      REDIS_HOST: redis
      REDIS_PORT: 6379 # Using default redis image port
    restart: 'no' # TODO: change this to 'always' on production
  mysql:
    image: "mysql"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "[ mysql_root_password ]" # TODO: change this to a strong password on production, for administration purposes
      MYSQL_DATABASE: egov-jabar
      MYSQL_USER: egov-jabar
      MYSQL_PASSWORD: "[ mysql_password ]" # TODO: change this to a strong password on production, must match with app
    restart: on-failure # TODO: change this to 'always' on production
  redis:
    image: "redis:alpine"
    restart: on-failure # TODO: change this to 'always' on production
  myadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
        - "1000:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
    restart: unless-stopped
    depends_on:
        - mysql
  #rethinkdb:
  #  image: rethinkdb
  #  restart: on-failure
  #  ports:
  #      - "28015:28015"
  #      - "1001:8080"